services:
  backend:
    container_name: laravel
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:oYtkXVoqvanhfEJyWubSoloLKHg1Ukbfem+Eww22RUw=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      LOG_CHANNEL: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: carplex
      DB_USERNAME: carplex_user
      DB_PASSWORD: P@ssword123
    volumes:
      - ./backend:/var/www/html/backend
      - enlive-vendor:/var/www/html/backend/vendor
      - ./backend/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - app
  frontend:
    container_name: next_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /var/www/html/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app
  db:
    container_name: db
    image: mariadb:12.2.2-ubi10
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: carplex
      MYSQL_USER: carplex_user
      MYSQL_PASSWORD: P@ssword123
      MYSQL_ROOT_PASSWORD: P@ssword123
    networks:
      - app
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/backend
      - enlive-vendor:/var/www/html/backend/vendor
      - ./frontend:/var/www/html/frontend
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  enlive-vendor:
